import React from "react";
import { Composition } from "remotion";
import { Short, shortSchema } from "./Short";

// render-props.json is generated by the Python pipeline before rendering.
// Defaults below let you open Remotion Studio without the pipeline.
export const RemotionRoot: React.FC = () => {
  return (
    <Composition
      id="Short"
      component={Short}
      durationInFrames={1800}
      fps={30}
      width={1080}
      height={1920}
      schema={shortSchema}
      defaultProps={{
        title: "Claude ships a huge dev update",
        topicTitle: "Claude updates",
        accent: "#E17055",
        accent2: "#ff9a76",
        pattern: "rings",
        heroImage: "",
        audioSrc: "voice.mp3",
        durationSeconds: 55,
        words: [],
        lines: [
          "Here's what just changed with Claude and why it matters.",
          "There's a brand-new tag that lets developers review AI work.",
          "It plugs straight into your pull request flow.",
          "So you ship faster without losing control.",
          "Follow for a fresh AI update every single day.",
        ],
        points: [
          { heading: "New Claude Tag", detail: "Mark AI-written code for review" },
          { heading: "PR-native", detail: "Works inside your pull requests" },
          { heading: "Faster reviews", detail: "Less back-and-forth on changes" },
        ],
        flow: ["You prompt", "Claude drafts", "You review", "Merged"],
      }}
      // Pull real duration from props so video length always matches the audio.
      calculateMetadata={({ props }) => ({
        durationInFrames: Math.ceil((props.durationSeconds + 0.6) * 30),
      })}
    />
  );
};
